# Generated by Django 3.2.9 on 2021-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='duration',
        ),
        migrations.DeleteModel(
            name='OneTimeAmount',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='applied_discount',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='company',
        ),
        migrations.DeleteModel(
            name='PerEmployeeAmount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='PaymentDuration',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
