# Generated by Django 3.2.9 on 2021-12-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211216_1819'),
        ('payments', '0003_freetrial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_tokens', to='app.company')),
            ],
        ),
    ]
