# Generated by Django 3.2.7 on 2021-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staff_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyschedule',
            name='end_work',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Ish Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='lunch_end',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Tushlik tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='lunch_start',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Tushlik vaqti'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='start_work',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Ish boshlanishi'),
        ),
    ]
