# Generated by Django 3.2.9 on 2021-12-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211102_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company/files')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('adopt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adoptationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptationUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AdoptationVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='company/video')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adoptationquestions')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company/files')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('adopt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adoptationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='company/video')),
            ],
        ),
        migrations.RemoveField(
            model_name='traininginfo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='traininginfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='trainingquestion',
            name='position',
        ),
        migrations.AddField(
            model_name='flow',
            name='came_lunch',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ovqatdan kelish'),
        ),
        migrations.AddField(
            model_name='flow',
            name='went_lunch',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ovqatga ketish'),
        ),
        migrations.AddField(
            model_name='salary',
            name='work_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('intern', 'Intern')], default='full time', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_outsource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='additionalpayments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='additionalpaymenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyculture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyschedulename',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companyschedulename',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entrytext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='finishtext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Miqdori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='attached_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Biriktirilgan sana'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Yankunlangan sana'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='type_of_work',
            field=models.CharField(default='kunbay', max_length=255, verbose_name='Ishlash turi(soatbay, kunbay, ishbay ...)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stafforgsystem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='superstaffs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='companyschedulename',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('company', 'username')},
        ),
        migrations.DeleteModel(
            name='TrainingAnswer',
        ),
        migrations.DeleteModel(
            name='TrainingInfo',
        ),
        migrations.DeleteModel(
            name='TrainingQuestion',
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationFiles'),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Xodimning lavozimi'),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='urls',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationUrls'),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='videos',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationVideos'),
        ),
        migrations.AddField(
            model_name='staffanswers',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AddField(
            model_name='adoptationmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='adoptationmodel',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationFiles'),
        ),
        migrations.AddField(
            model_name='adoptationmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Xodimning lavozimi'),
        ),
        migrations.AddField(
            model_name='adoptationmodel',
            name='urls',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationUrls'),
        ),
        migrations.AddField(
            model_name='adoptationmodel',
            name='videos',
            field=models.ManyToManyField(blank=True, default=None, to='app.AdoptationVideos'),
        ),
        migrations.AlterUniqueTogether(
            name='staffanswers',
            unique_together={('question', 'staff')},
        ),
    ]
