# Generated by Django 3.2.9 on 2021-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211214_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_expire_data',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="To'lov muddati"),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="To'lagan summasi"),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name="Bir martalik to'lov statusi"),
        ),
    ]
