# Generated by Django 3.2.9 on 2021-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211214_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_expire_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov tugash muddati"),
        ),
    ]
