# Generated by Django 3.2.9 on 2021-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_company_payment_expire_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_paid',
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_expire_data',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="To'lov tugash muddati"),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
