# Generated by Django 3.2.9 on 2021-12-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211216_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='payment_expire_data',
            new_name='payment_expire_date',
        ),
    ]
