# Generated by Django 3.2.9 on 2021-12-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_payment_expire_data_company_payment_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov tugash muddati"),
        ),
    ]
